[package]
name = "dedup"
version = "0.1.0"
authors = ["Sriharsha Mucheli <harshasrisri@gmail.com>"]

[dependencies]
md-5 = "0.8"
sha-1 = "0.8"
sha2 = "0.8"
digest = "0.8"
ignore = "0.4"
structopt = "0.2"
